# Generated by Django 5.1 on 2024-08-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_appliedpost_status_job_seeker_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
