# Generated by Django 5.0.1 on 2024-08-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_job_seeker_latitude_job_seeker_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='location',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
    ]
