# Generated by Django 5.1 on 2024-08-21 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_rename_content_message_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-08-21T12:34:56Z'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job_post'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job_seeker'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.recruiter'),
        ),
    ]
