# Generated by Django 5.1 on 2024-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_remove_message_chat_room_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_seeker',
            name='custom_user_id',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='custom_user_id',
        ),
    ]
