# Generated by Django 5.1 on 2024-08-21 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0026_remove_job_seeker_custom_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker',
            name='custom_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='custom_user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
