# Generated by Django 5.1 on 2024-08-21 23:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_remove_job_seeker_custom_user_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='thread',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='App.thread'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='job_seeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='App.job_seeker'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='App.recruiter'),
        ),
        migrations.RemoveField(
            model_name='thread',
            name='updated',
        ),
    ]
