# Generated by Django 5.1 on 2024-08-22 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_chatmessage_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='read',
        ),
    ]
